### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by perryao** [archlinux/arch-boxes#28] opened 2018-05-06 18:10 UTC
Getting this error with a fresh vagrant up:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: Invalid argument

```

I'm guessing this is because VirtualBox guest additions aren't installed: https://www.vagrantup.com/docs/virtualbox/boxes.html#virtualbox-guest-additions

**Comment by rafaelsoaresbr** [comment] 2018-05-06 18:32
Does this happen after running vagrant up?
@shibumi maybe vagrant up runs this command as vagrant. Adding vagrant user to vboxfs group should fix this.

**Comment by shibumi** [comment] 2018-05-06 20:11
This issue seems to be related to vagrant. We are installing already the virtualbox additions into the guest VM: https://github.com/archlinux/arch-boxes/blob/master/provision/virtualbox.sh

@perryao can you try this with any other box? I am pretty sure your vagrant is wrong configured.

**Comment by rafaelsoaresbr** [comment] 2018-05-06 21:42
Probably, I've tried to reproduce this but I'm on a very slow internet connection.

**Comment by chriswayg** [comment] 2018-05-07 16:40
I get a similar error, even though Vagrant is configured correctly, as other standard boxes (bento/...) run without error. vboxservice is running inside arch. 

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount.vboxsf cannot be used with mainline vboxsf; instead use:

    mount -cit vboxsf NAME MOUNTPOINT
```

macOS Sierra 10.12.6, Vagrant 2.0.4, Virtualbox 5.2.10 r122088

**Comment by shibumi** [comment] 2018-05-08 14:43
Mhh indeed. There seems to be a bug in vagrant:
```
==> default: Mounting shared folders...
    default: /vagrant => /home/chris
#<Thread:0x00005595b2ea6f08@/opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	117: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	116: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/machine.rb:188:in `action'
	115: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/machine.rb:188:in `call'
	114: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/environment.rb:598:in `lock'
	113: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/machine.rb:202:in `block in action'
	112: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/machine.rb:227:in `action_raw'
	111: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	110: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	109: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	108: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	107: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	106: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	105: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	104: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	103: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	102: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	101: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	100: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	 99: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 98: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 97: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 96: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 95: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 94: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 93: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 92: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 91: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 90: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	 89: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	 88: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	 87: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	 86: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	 85: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 84: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 83: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 82: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 81: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 80: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	 79: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 78: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	 77: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 76: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	 75: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 74: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/import.rb:13:in `call'
	 73: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/import.rb:74:in `import'
	 72: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 71: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	 70: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 69: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
	 68: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 67: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 66: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 65: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	 64: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 63: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 62: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 61: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_check_outdated.rb:79:in `call'
	 60: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 59: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	 58: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	 57: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	 56: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	 55: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	 54: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 53: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 52: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 51: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	 50: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	 49: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	 48: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	 47: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	 46: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 45: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 44: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 43: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	 42: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	 41: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	 40: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	 39: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	 38: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 37: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 36: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 35: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 34: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 33: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	 32: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 31: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 30: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 29: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 28: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 27: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
	 26: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 25: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 24: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 23: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	 22: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 21: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:49:in `call'
	 20: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 19: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	 18: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 17: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	 16: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 15: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	 14: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	 13: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/synced_folders.rb:90:in `call'
	 12: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/synced_folders.rb:90:in `each'
	 11: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/action/builtin/synced_folders.rb:93:in `block in call'
	 10: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/synced_folder.rb:36:in `enable'
	  9: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/synced_folder.rb:36:in `each'
	  8: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/providers/virtualbox/synced_folder.rb:52:in `block in enable'
	  7: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/guest.rb:43:in `capability'
	  6: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/capability_host.rb:111:in `capability'
	  5: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/capability_host.rb:111:in `call'
	  4: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb:30:in `mount_virtualbox_shared_folder'
	  3: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/lib/vagrant/util/retryable.rb:17:in `retryable'
	  2: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb:31:in `block in mount_virtualbox_shared_folder'
	  1: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/communicators/ssh/communicator.rb:276:in `sudo'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.4/plugins/communicators/ssh/communicator.rb:266:in `execute': Vagrant was unable to mount VirtualBox shared folders. This is usually (Vagrant::Errors::VirtualBoxMountFailed)
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount.vboxsf cannot be used with mainline vboxsf; instead use:

    mount -cit vboxsf NAME MOUNTPOINT

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount.vboxsf cannot be used with mainline vboxsf; instead use:

    mount -cit vboxsf NAME MOUNTPOINT
```

**Comment by shibumi** [comment] 2018-05-08 14:44
You can try to run the box from april and update the box manually after it. This should work:

`vagrant init archlinux/archlinux --box-version 2018.04.05`

**Comment by perryao** [comment] 2018-05-08 15:13
@shibumi that works without error. Thanks for the workaround.

**Comment by graudeejs** [comment] 2018-05-08 15:51
Just note that if you use `vagrant init archlinux/archlinux --box-version 2018.04.05`, you should `rm -Rf /usr/bin/mount.vboxsf` or else after you halt and start your VM, it won't be able to automatically mount shared directory.

**Comment by shibumi** [comment] 2018-05-08 15:53
btw the issue seems to be fixed in vagrant 2.1.1.. just in case somebody want to update their vagrant. Because I am pretty sure this behaviour will be broken in future builds as well (except i start shipping linux-lts instead of linux)

**Comment by graudeejs** [comment] 2018-05-08 16:11
@shibumi Thanks. Just checked and it really works

**Comment by shibumi** [comment] 2018-05-08 18:46
I guess I can close this due to the fact that the issue is connected to the vagrant version and the kernel version of the guest.

**Closed by shibumi** 2018-05-08 18:46 UTC
Labels: bug-in-vagrant

**Comment by mborko** [comment] 2019-08-05 08:31
Have I missed something, I've got this message at the start process again:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

: Invalid argument
```

The guest box is ```'archlinux/archlinux' version '2019.07.05'``` and the host is running following versions:
* community/virtualbox 6.0.10-1 [installed]
* community/virtualbox-guest-iso 6.0.10-1 [installed]
* community/virtualbox-guest-modules-arch 6.0.10-5 [installed]
* community/virtualbox-host-modules-arch 6.0.10-5 [installed]
* community/vagrant 2.2.5-1 [installed]

The command ```mount -cit vboxsf vagrant /vagrant``` is working, but it would be great if automount would also work. Any suggestions?

**Comment by mborko** [comment] 2019-08-05 08:38
> Have I missed something, I've got this message at the start process again:
> 
> ```
> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest. This is not a bug in Vagrant and is usually caused by a faulty
> Vagrant box. For context, the command attempted was:
> 
> mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant
> 
> The error output from the command was:
> 
> : Invalid argument
> ```
> 
> The guest box is `'archlinux/archlinux' version '2019.07.05'` and the host is running following versions:
> 
>     * community/virtualbox 6.0.10-1 [installed]
> 
>     * community/virtualbox-guest-iso 6.0.10-1 [installed]
> 
>     * community/virtualbox-guest-modules-arch 6.0.10-5 [installed]
> 
>     * community/virtualbox-host-modules-arch 6.0.10-5 [installed]
> 
>     * community/vagrant 2.2.5-1 [installed]
> 
> 
> The command `mount -cit vboxsf vagrant /vagrant` is working, but it would be great if automount would also work. Any suggestions?

The newest version ```2019.08.05``` of the box solved the issue.
