### ISSUE TITLE
vboxguest not found ?

### ISSUE THREAD

**Issue by thepenguinthatwants** [archlinux/arch-boxes#42] opened 2019-07-28 14:07 UTC
When I ran 

`vagrant init archlinux/archlinux`

`vagrant up`

```
==> default: Mounting shared folders...
    default: /vagrant => /home/daenar/vagrant/arch
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:


mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant



The error output from the command was:

/usr/bin/mount.vboxsf: mounting failed with the error: Invalid argument
```

**Comment by shibumi** [comment] 2019-08-03 21:40
Interesting. I will have a look into this.

**Comment by shibumi** [comment] 2019-08-04 18:19
I definitely can't reproduce this.. On which host system are you? which virtualbox version, which vagrant version, etc? Can you reproduce this issue?

```
chris motoko /tmp 20:05:55  
❯ vagrant init archlinux/archlinux
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
chris motoko /tmp 20:06:02  
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'archlinux/archlinux' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'archlinux/archlinux'
    default: URL: https://vagrantcloud.com/archlinux/archlinux
==> default: Adding box 'archlinux/archlinux' (v2019.07.05) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/archlinux/boxes/archlinux/versions/2019.07.05/providers/virtualbox.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'archlinux/archlinux' (v2019.07.05) for 'virtualbox'!
==> default: Importing base box 'archlinux/archlinux'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'archlinux/archlinux' version '2019.07.05' is up to date...
==> default: Setting the name of the VM: tmp_default_1564942413347_14547
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /tmp
'vagrant up' time: 7:54.42s, cpu: 6%
chris motoko /tmp 20:13:59  
❯ date
Sun 04 Aug 2019 08:15:59 PM CEST
chris motoko /tmp 20:15:59  
❯ uname -a 
Linux motoko.nullday.de 4.19.61-1-lts #1 SMP Fri Jul 26 10:27:00 CEST 2019 x86_64 GNU/Linux
chris motoko /tmp 20:16:08  
❯ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
chris motoko /tmp 20:16:27  
❯ vagrant ssh
[vagrant@archlinux ~]$ pacman -Syu
error: you cannot perform this operation unless you are root.
[vagrant@archlinux ~]$ sudo pacman -Syu
:: Synchronizing package databases...
 core                                      132.5 KiB   996K/s 00:00 [######################################] 100%
 extra                                    1630.1 KiB  2.73M/s 00:01 [######################################] 100%
 community                                   4.9 MiB  2.36M/s 00:02 [######################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (29) btrfs-progs-5.2.1-1  bzip2-1.0.8-2  ca-certificates-mozilla-3.45-1  curl-7.65.3-1
              e2fsprogs-1.45.3-1  glib2-2.60.6-1  glibc-2.29-4  gnupg-2.2.17-2  gnutls-3.6.9-1  grub-2:2.04-2
              iana-etc-20190722-1  iproute2-5.2.0-1  js60-60.8.0-1  ldns-1.7.1-1  libtasn1-4.14-1
              linux-5.2.5.arch1-1  linux-firmware-20190717.bf13a71-1  nettle-3.5.1-1  openresolv-3.9.1-1
              openssh-8.0p1-2  s-nail-14.9.14-1  shadow-4.7-1  sqlite-3.29.0-1  systemd-242.84-1
              systemd-libs-242.84-1  systemd-sysvcompat-242.84-1  virtualbox-guest-modules-arch-6.0.10-5
              virtualbox-guest-utils-nox-6.0.10-1  zstd-1.4.1-1

Total Download Size:   204.01 MiB
Total Installed Size:  775.04 MiB
Net Upgrade Size:       17.19 MiB

:: Proceed with installation? [Y/n] n
[vagrant@archlinux ~]$ pacman-key --populate archlinux
==> ERROR: pacman-key needs to be run as root for this operation.
[vagrant@archlinux ~]$ sudo pacman-key --populate archlinux
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D8AFDDA07A5B6EDFA7D8CCDAD6D055F927843F1C...
  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
==> Importing owner trust values...
==> Disabling revoked keys in keyring...
  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...
  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...
  -> Disabling key 50F33E2E5B0C3D900424ABE89BDCF497A4BBCC7F...
  -> Disabling key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...
  -> Disabling key 39F880E50E49A4D11341E8F939E4F17F295AFBF4...
  -> Disabling key 8840BD07FC24CB7CE394A07CCF7037A4F27FB7DA...
  -> Disabling key 5559BC1A32B8F76B3FCCD9555FA5E5544F010D48...
  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...
  -> Disabling key 07DFD3A0BC213FA12EDC217559B3122E2FA915EC...
  -> Disabling key 4FCF887689C41B09506BE8D5F3E1D5C5D30DB0AD...
  -> Disabling key 5A2257D19FF7E1E0E415968CE62F853100F0D0F0...
  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...
  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...
  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...
  -> Disabling key 5696C003B0854206450C8E5BE613C09CB4440678...
  -> Disabling key 8CF934E339CAD8ABF342E822E711306E3C4F88BC...
  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...
  -> Disabling key 5E7585ADFF106BFFBBA319DC654B877A0864983E...
  -> Disabling key 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A...
  -> Disabling key 40440DC037C05620984379A6761FAD69BA06C6A9...
  -> Disabling key 34C5D94FE7E7913E86DC427E7FB1A3800C84C0A5...
  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...
  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...
  -> Disabling key 5357F3B111688D88C1D88119FCF2CB179205AC90...
  -> Disabling key FB871F0131FEA4FB5A9192B4C8880A6406361833...
  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
  -> Disabling key B1F2C889CB2CCB2ADA36D963097D629E437520BD...
  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...
  -> Disabling key 40776A5221EF5AD468A4906D42A1DB15EC133BAD...
  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...
  -> Disabling key 44D4A033AC140143927397D47EFD567D4C7EA887...
==> Updating trust database...
gpg: next trustdb check due at 2019-10-03
[vagrant@archlinux ~]$ 
```

**Comment by thepenguinthatwants** [comment] 2019-09-02 19:11
I am using Archlinux
Vagrant 2.2.5
virtualbox 6.0.10-1

The problem still persists

**Comment by thepenguinthatwants** [comment] 2019-09-02 19:20
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/daenar/vagrant/arch
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/usr/bin/mount.vboxsf: mounting failed with the error: Invalid argument


But then when I used

`vagrant ssh`

Last login: Mon Sep  2 19:16:52 2019 from 10.0.2.2
[vagrant@archlinux ~]$ 

So it seems like it build and worked but that problem is about shared folders.

**Comment by shibumi** [comment] 2019-09-03 08:29
@thepenguinthatwants did you enable the needed kernel modules on your host?
```
sudo modprobe vboxdrv   
sudo modprobe vboxnetadp
sudo modprobe vboxnetflt
```

**Comment by thepenguinthatwants** [comment] 2019-09-03 12:38
Hi!

Yeah I just tried those commands but still getting the same error.

**Comment by shibumi** [comment] 2019-09-04 15:19
I have no idea why I can't reproduce this issue on my system:
```
chris motoko /tmp 17:11:40  
❯ vagrant init archlinux/archlinux
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
chris motoko /tmp 17:11:46  
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'archlinux/archlinux' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'archlinux/archlinux'
    default: URL: https://vagrantcloud.com/archlinux/archlinux
==> default: Adding box 'archlinux/archlinux' (v2019.08.05) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/archlinux/boxes/archlinux/versions/2019.08.05/providers/virtualbox.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'archlinux/archlinux' (v2019.08.05) for 'virtualbox'!
==> default: Importing base box 'archlinux/archlinux'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'archlinux/archlinux' version '2019.08.05' is up to date...
==> default: Setting the name of the VM: tmp_default_1567610106641_81025
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /tmp
```

But you are not the only one who has such problems.

**Comment by shibumi** [comment] 2019-09-04 15:22
Ok, next question. Do you have virtualbox-host-dksm or virtualbox-host-modules-arch installed?

**Comment by eli-schwartz** [comment] 2019-09-04 15:26
Please post the output of:

```
pacman -Q linux
uname -a
pacman -Qs virtualbox
```

**Comment by thepenguinthatwants** [comment] 2019-09-05 13:51
The output is:

`linux 5.2.11.arch1-1`

`Linux ninja 5.2.11-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 29 08:09:36 UTC 2019 x86_64 GNU/Linux`


```
local/virtualbox 6.0.10-1
    Powerful x86 virtualization for enterprise as well as home use
local/virtualbox-host-modules-arch 6.0.10-11
    Virtualbox host kernel modules for Arch Kernel
```

**Comment by shibumi** [comment] 2019-09-06 02:13
@thepenguinthatwants can you try using `virtualbox-host-dkms` instead of `virtualbox-host-modules-arch`? I know, there should the be same, but I want to make sure that your setup looks like mine.

**Comment by thepenguinthatwants** [comment] 2019-09-06 20:56
Hi!

I tried the virtualbox-host-dkms and rebooted computer too. But still the same warning.

**Comment by shibumi** [comment] 2019-09-06 21:11
Hi @thepenguinthatwants one question: Which user to do you use to start the box? and could you do `id <your username`? Is your user in the group `vboxusers`?

**Comment by thepenguinthatwants** [comment] 2019-09-07 20:51
Hi!

Using the ninja user.

uid=1000(ninja) gid=985(users) groups=985(users),998(wheel),972(docker),1000(fuse),108(vboxusers)

Actually didn't even have the whole vboxusers group. 
So I just 
sudo gpasswd -a ninja vboxusers
Then rebooted computer and still the same error.

**Comment by shibumi** [comment] 2019-09-07 23:02
Mh interesting,
ok what do these commands show:
``` bash
cat /proc/filesystems 
modprobe -l vboxsf
lsmod | grep vboxsf
```

What happens when you do:
```bash
modprobe vboxsf
# then as normal user:
vagrant init archlinux/archlinux
vagrant up
```

**Comment by thepenguinthatwants** [comment] 2019-09-09 12:34
`cat /proc/filesystems `

output:
```
nodev   sysfs
nodev   rootfs
nodev   ramfs
nodev   bdev
nodev   proc
nodev   cpuset
nodev   cgroup
nodev   cgroup2
nodev   tmpfs
nodev   devtmpfs
nodev   binfmt_misc
nodev   configfs
nodev   debugfs
nodev   tracefs
nodev   securityfs
nodev   sockfs
nodev   dax
nodev   bpf
nodev   pipefs
nodev   hugetlbfs
nodev   devpts
nodev   autofs
nodev   efivarfs
nodev   mqueue
nodev   pstore
        ext3
        ext2
        ext4
        vfat
        fuseblk
nodev   fuse
nodev   fusectl
nodev   overlay
```
`modprobe: invalid option -- 'l'`

`modprobe: FATAL: Module vboxsf not found in directory /lib/modules/5.2.11-arch1-1-ARCH`

**Comment by shibumi** [comment] 2019-09-09 12:49
Ok, it's definitely guest related.
Can you do `systemctl status vboxservice` inside of the vagrant guest? It should look like this:
```
chris motoko ~/vagrant 14:45:47 10d567bf master  
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'archlinux/archlinux'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'archlinux/archlinux' version '2019.08.05' is up to date...
==> default: Setting the name of the VM: vagrant_default_1568033277353_57379
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/chris/vagrant
'vagrant up' time: 2:31.19s, cpu: 6%
chris motoko ~/vagrant 14:48:19 10d567bf master  
❯ vagrant ssh
[vagrant@archlinux ~]$ systemctl status vboxservice
● vboxservice.service - VirtualBox Guest Service
   Loaded: loaded (/usr/lib/systemd/system/vboxservice.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-09 12:48:06 UTC; 40s ago
  Process: 353 ExecStartPre=/usr/bin/modprobe vboxguest (code=exited, status=0/SUCCESS)
  Process: 355 ExecStartPre=/usr/bin/modprobe vboxsf (code=exited, status=0/SUCCESS)
 Main PID: 363 (VBoxService)
    Tasks: 8 (limit: 1164)
   Memory: 3.0M
   CGroup: /system.slice/vboxservice.service
           └─363 /usr/bin/VBoxService -f

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[vagrant@archlinux ~]$ 
```

**Comment by shibumi** [comment] 2019-09-09 12:52
Another idea is, doing this: ` VAGRANT_LOG=info vagrant up`

**Comment by shibumi** [comment] 2019-09-09 17:17
@thepenguinthatwants So @SantiagoTorres was so nice and had a look on this issue as well, he saw that you have `vagrant-vbguest` installed as vagrant plugin. Seems like I missed that.
So I installed `vagrant-vbguest` as well and after a big bunch of output that you forgot to attach, I ran into the same error messages like you. Therefore it's clearly related to that plugin.

**Comment by shibumi** [comment] 2019-09-09 17:19
When trying removing the plugin I ran into this:
```
❯ vagrant plugin uninstall vagrant-vbguest
Uninstalling the 'vagrant-vbguest' plugin...
Traceback (most recent call last):
	27: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'
	26: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
	25: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
	24: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/command/root.rb:66:in `execute'
	23: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/command/uninstall.rb:25:in `execute'
	22: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/command/uninstall.rb:25:in `each'
	21: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/command/uninstall.rb:26:in `block in execute'
	20: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/command/base.rb:14:in `action'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `run'
	18: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `block in run'
	16: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/builder.rb:116:in `call'
	15: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/action/plugin_exists_check.rb:20:in `call'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
	10: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	 9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
	 8: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/plugins/commands/plugin/action/uninstall_plugin.rb:18:in `call'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/plugin/manager.rb:200:in `uninstall_plugin'
	 4: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:242:in `clean'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:242:in `each'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:251:in `block in clean'
	 1: from /usr/lib/ruby/2.6.0/rubygems/uninstaller.rb:162:in `uninstall_gem'
/usr/lib/ruby/2.6.0/rubygems/uninstaller.rb:264:in `remove': uninitialized constant Gem::RDoc (NameError)
```

**Comment by shibumi** [comment] 2019-09-09 17:22
I am going to close this issue, because for me it looks like an issue inside of your plugin.

**Closed by shibumi** 2019-09-09 17:22 UTC
Labels: bug, invalid
